spring:
  datasource:
    url: jdbc:mysql://localhost:3306/japanese_learning?createDatabaseIfNotExist=true
    username: root
    password: 12345Qwert!!
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect